"""add changes oplog table

Revision ID: 66a77cdf47d1
Revises: 80374874805b
Create Date: 2026-08-23 20:36:04.126477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66a77cdf47d1"
down_revision: Union[str, Sequence[str], None] = "80374874805b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "changes",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("op", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("origin_device", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        op.f("ix_changes_object_id"), "changes", ["object_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_changes_object_id"), table_name="changes")
    op.drop_table("changes")
    # ### end Alembic commands ###
