"""add version and deleted_at for sync

Revision ID: 8217e878a01a
Revises: e9e78081f4a7
Create Date: 2026-08-23 20:29:13.580385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8217e878a01a"
down_revision: Union[str, Sequence[str], None] = "e9e78081f4a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attachments",
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column("attachments", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "items", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("items", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "deleted_at")
    op.drop_column("items", "version")
    op.drop_column("attachments", "deleted_at")
    op.drop_column("attachments", "version")
    # ### end Alembic commands ###
