"""add arxiv_id to items

Revision ID: 92a7ff39606e
Revises: 74d1cd19b77c
Create Date: 2026-06-14 23:03:20.754239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92a7ff39606e"
down_revision: Union[str, Sequence[str], None] = "74d1cd19b77c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items") as batch_op:
        batch_op.add_column(sa.Column("arxiv_id", sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint("uq_items_arxiv_id", ["arxiv_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items") as batch_op:
        batch_op.drop_constraint("uq_items_arxiv_id", type_="unique")
        batch_op.drop_column("arxiv_id")
    # ### end Alembic commands ###
