"""add connector_sessions table

Revision ID: e9e78081f4a7
Revises: 92a7ff39606e
Create Date: 2026-06-15 00:52:52.416673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e9e78081f4a7"
down_revision: Union[str, Sequence[str], None] = "92a7ff39606e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("item_map", sa.JSON(), nullable=False),
        sa.Column("attachment_map", sa.JSON(), nullable=False),
        sa.Column("pending_attachments", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_sessions_session_id"),
        "connector_sessions",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_connector_sessions_session_id"), table_name="connector_sessions"
    )
    op.drop_table("connector_sessions")
    # ### end Alembic commands ###
